module.exports = Object.freeze
({
    ACCESS_COLS:     "access_collections",
    ACCESS_MAPS:     "access_maps",
    AREAS:           "areas",
    BOUNDARIES_COLS: "boundaries_collections",
    BOUNDARIES_MAPS: "boundaries_maps",
    LIGHT_COLS:      "light_collections",
    LIGHT_MAPS:      "light_maps",
    MOVING_COLS:     "moving_collections",
    MOVING_MAPS:     "moving_maps",
    NATURE_COLS:     "nature_collections",
    NATURE_MAPS:     "nature_maps",
    ORDER_COLS:      "order_collections",
    ORDER_MAPS:      "order_maps",
    PROGRAM_COLS:    "program_collections",
    PROGRAM_FLOORS:  "program_floors",
    PROGRAM_MAPS:    "program_maps",
    PROJECTS:        "projects",
    SECTION_MAPS:    "section_maps",
    SECTION_COLS:    "section_collections",
    SOUND_COLS:      "sound_collections",
    SOUND_MAPS:      "sound_maps",
    STANDING_POINTS: "standing_points",
    STATIONARY_COLS: "stationary_collections",
    STATIONARY_MAPS: "stationary_maps",
    SURVEY_COLS:     "survey_collections",
    SURVEY_KEYS:     "survey_key_trackers",
    SURVEYS:         "surveys",
    TEAMS:           "teams",
    USERS:           "users",
});
